const CONNECTIONS_KEY = 'arlo-connection-consents';
const apps = [
  { id: 'magnus-ai', name: 'Magnus AI', kind: 'Website builder', description: 'Let Arlo send approved site changes, content, and build instructions to Magnus AI.', scope: 'Only approved website projects and actions.' },
  { id: 'notion', name: 'Notion', kind: 'Workspace notes', description: 'Create or update notes and summaries in selected Notion pages.', scope: 'Only pages and databases you choose.' },
  { id: 'obsidian', name: 'Obsidian', kind: 'Local vault', description: 'Write approved notes and call summaries into a selected local vault.', scope: 'Only the vault folder you grant.' },
];
function consents(){try{return JSON.parse(sessionStorage.getItem(CONNECTIONS_KEY)||'{}')}catch{return {}}}
function save(value){sessionStorage.setItem(CONNECTIONS_KEY,JSON.stringify(value));}
function openPanel(){if(document.querySelector('.connections-panel'))return;const panel=document.createElement('section');panel.className='connections-panel card';panel.innerHTML=`<div class="connections-head"><div><span class="eyebrow">Permission center</span><h2>Connect your apps</h2><p class="muted">Arlo can set up the connection after you approve the exact access requested.</p></div><button class="delete" data-close-connections>×</button></div><div class="connection-list">${apps.map(app=>{const active=consents()[app.id];return `<article class="connection-row"><div class="connection-icon">${app.id==='magnus-ai'?'M':app.id==='notion'?'N':'O'}</div><div class="connection-copy"><h3>${app.name} <small>${app.kind}</small></h3><p>${app.description}</p><small class="muted">Scope: ${app.scope}</small></div><button class="${active?'ghost':'primary'}" data-connect="${app.id}">${active?'Revoke':'Connect'}</button></article>`}).join('')}</div><div class="notice">No app receives data until you approve it. Real OAuth or local-folder authorization will replace this prototype consent step during adapter setup.</div>`;document.querySelector('.content')?.appendChild(panel);panel.querySelector('[data-close-connections]').onclick=()=>panel.remove();panel.querySelectorAll('[data-connect]').forEach(button=>button.onclick=()=>{const id=button.dataset.connect;const app=apps.find(item=>item.id===id);const current=consents();if(current[id]){delete current[id];save(current);openPanel();return;}if(confirm(`Allow Arlo to connect to ${app.name}? Arlo will request only the access described in this panel.`)){current[id]={approvedAt:new Date().toISOString(),status:'awaiting-provider-auth'};save(current);alert(`${app.name} permission approved. The provider authorization step will open when this connector is installed.`);openPanel();}});}
const observer=new MutationObserver(()=>{if(document.querySelector('.shell')&&!document.querySelector('[data-connections-button]')){const button=document.createElement('button');button.className='connections-fab';button.dataset.connectionsButton='true';button.textContent='Connect apps';button.onclick=openPanel;document.body.appendChild(button);}});observer.observe(document.body,{childList:true,subtree:true});
